safe-global/safe-apps-sdk

- .eslintrc.js
- .travis.yml
- package.json
- src/index.test.ts
- src/index.ts
- tsconfig.json
- yarn.lock
This PR:
- Setup eslint
- Improve type definitions
- Update dependencies to the latest version
> #20 Improve type definitions

- README.md
https://docs.google.com/document/d/1YRGlaNo-E88I-EhHLMPKjSP38DInFgtRwEUpy8rPMyI/edit
> Changes after user test: Add ipfs info and link to existing apps in devportal

- README.md
This PR: 
- Add npm version badge to the readme
> Add npm version badge to readme

- package.json
- src/types.ts
- xDAI
- Volta
- EWC
Closes #53.
> Feature: Add networks support

- README.md
- packages/safe-apps-ethers-provider/README.md
- packages/safe-apps-ethers-provider/package.json
- packages/safe-apps-ethers-provider/src/index.ts
- packages/safe-apps-ethers-provider/src/provider.ts
- packages/safe-apps-ethers-provider/src/utils.ts
- packages/safe-apps-ethers-provider/tsconfig.json
- packages/safe-apps-react-sdk/README.md
- packages/safe-apps-react-sdk/package.json
- packages/safe-apps-sdk/package.json
- yarn.lock
This PR:
- Adds ethers provider implementation based on https://github.com/rmeissner/sapp-phenix/blob/28148fef3d686342220b10d94d15dea8f51fb94e/src/safe/provider.ts
> Feature: Add ethers provider

- .github/workflows/cla.yml
This PR:
- Adds CLA GitHub action and closes #84
> Add CLA github action

- packages/safe-apps-onboard/package.json
- packages/safe-apps-web3modal/package.json
This PR:
- Release 0.2.1 which is equal to 0.2.0 but 0.2.0 was missing files
> Web3modal/onboard integraitons 0.2.1

- README.md
The template was moved so we need to update the link.
> Update the CRA template link in the readme

- packages/safe-apps-sdk/src/eth/index.ts
- packages/safe-apps-sdk/src/sdk.ts
- packages/safe-apps-sdk/src/txs/index.ts
> fix: remove ES6 private fields to aid compatibility

- .github/workflows/devui-ci.yml
Make CI work with dev-ui/vX.Y.Z naming convention
> Make CI work with dev-ui/vX.Y.Z naming convention

- README.md
Add a section about testing safe apps to README
> Add a section about testing safe apps to README

- .github/workflows/release.yml
- README.md
- docs/releases.md
- package.json
- yarn.lock
This PR adds a new release workflow that takes care of versioning, changelogs, github releases, etc using [changesets](https://github.com/atlassian/changesets). The process is described in [releases.md doc](https://github.com/gnosis/safe-apps-sdk/blob/5bfac213447de48f6fa436c7a29f8f70b30e0a53/docs/releases.md), please pay special attention to it as there's one nonobvious thing required for releasing beta packages: entering pre-release mode. This document needs to be written in a clear way that is easy to understand
> changesets release workflow

- .changeset/smooth-ads-wonder.md
- packages/safe-apps-provider/package.json
- packages/safe-apps-sdk/README.md
- packages/safe-apps-sdk/src/index.ts
- packages/safe-apps-sdk/src/safe/index.ts
- packages/safe-apps-sdk/src/safe/safe.test.ts
- packages/safe-apps-sdk/src/safe/signatures.ts
- yarn.lock
fixes #246 by making calculateMessageHash a method on the safe class and adjusting docs
> make calculateMessageHash a class method

- packages/safe-apps-provider/README.md
> Add `new` when creating a provider in readme for safe-apps-provider

- .changeset/pre.json
- .changeset/yellow-planes-carry.md
- packages/safe-apps-sdk/package.json
- packages/safe-apps-sdk/src/communication/methods.ts
- packages/safe-apps-sdk/src/safe/index.ts
- packages/safe-apps-sdk/src/safe/safe.test.ts
- packages/safe-apps-sdk/src/types/messaging.ts
- packages/safe-apps-sdk/src/types/sdk.ts
- yarn.lock
Added ChainInfo Types:
```
export type ChainInfo = {
chainName: string;
chainId: number;
shortName: string;
nativeCurrency: string;
};
export type SafeInfo = {
safeAddress: string;
chainId: number;
threshold: number;
owners: string[];
chainInfo: ChainInfo;
};
```
> Added ChainInfo types

- .github/workflows/release.yml
- docs/releases.md
Fixes #269 
To be merged after https://github.com/gnosis/changesets-action-github-releases/pull/1 is reviewed
> Update changesets action

- LICENSE.md
- README.md
- guides/drain-safe-app/README.md
- guides/drain-safe-app/app/README.md
- packages/cra-template-safe-app/template/README.md
- packages/safe-apps-provider/README.md
- packages/safe-apps-react-sdk/README.md
- packages/safe-apps-sdk/README.md
- packages/safe-apps-sdk/dist/package.json
- packages/safe-apps-sdk/package.json
- packages/safe-apps-web3-react/README.md
- packages/safe-apps-web3modal/README.md
I did some checks while updating the Safe docs to update information across all readme files trying to update broken links and updating information
> Update Readmes across packages

- packages/safe-apps-web3-react/README.md
- packages/safe-apps-web3modal/README.md
Adding some documentation in the README.md about issues in NextJS and how to workaround on them
> docs: Add information in README about dynamic imports using NextJS

- .changeset/pink-months-sniff.md
- packages/safe-apps-sdk/src/communication/index.ts
- packages/safe-apps-web3-react/README.md
fixes #317 by checking if the window is defined before accessing
> Fix next.js window is not defined error

- .changeset/stale-parrots-whisper.md
- .github/workflows/lint.yml
- package.json
- packages/safe-apps-react-sdk/package.json
- packages/safe-apps-sdk/package.json
- packages/safe-apps-web3-react/package.json
- packages/safe-apps-web3modal/package.json
- yarn.lock
Update dependencies across all packages. No major bumps.
I omitted upgrading react to 18 because IDK if it's backward compatible
> Chore: update dependencies

- packages/safe-apps-sdk/README.md
> Docs: Add ChainInfo to docs

- .github/workflows/cla.yml
I also changed my username to the actual one
> Update cla url in the cla action

- packages/safe-apps-sdk/dist/package.json
- packages/safe-apps-sdk/dist/src/types/gateway.d.ts
- packages/safe-apps-sdk/dist/src/types/gateway.js
- packages/safe-apps-sdk/dist/src/types/gateway.js.map
- packages/safe-apps-sdk/dist/src/types/sdk.d.ts
- packages/safe-apps-sdk/package.json
- packages/safe-apps-sdk/src/types/gateway.ts
- packages/safe-apps-sdk/src/types/sdk.ts
- yarn.lock
The Gateway SDK has been migrated to safe-global.
> Chore: migrate gateway sdk package to safe-global

- .changeset/config.json
- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
- guides/drain-safe-app/03-transfer-assets.md
- guides/drain-safe-app/app/README.md
- packages/cra-template-safe-app/template/README.md
- packages/cra-template-safe-app/template/src/App.tsx
- packages/safe-apps-provider/README.md
- packages/safe-apps-react-sdk/README.md
- packages/safe-apps-sdk/README.md
Rename all master references to main and switch the main branch
> Rename main branch from master to main

- .changeset/breezy-cooks-own.md
- packages/safe-apps-sdk/dist/package.json
- packages/safe-apps-test-app/src/tabs/RpcCalls/SafeSettings.tsx
Fix references to old package name
> fix: update old @gnosis.pm references with @safe-global

- packages/safe-apps-test-app/src/tabs/RpcCalls/SafeSettings.tsx
Type error in the example setting of Safe settings.
> fix: example app types

- .github/workflows/cla.yml
> chore: fix CLA link

- .changeset/pre.json
> Enter pre release mode

- .changeset/pre.json
Exit changeset pre mode to create a final release
> chore: exit changeset pre mode

- .changeset/soft-walls-share.md
- examples/wagmi/package.json
- examples/wagmi/src/components/Connect.tsx
- examples/wagmi/src/components/NetworkSwitcher.tsx
- examples/wagmi/src/index.tsx
- examples/wagmi/src/useAutoConnect.ts
- examples/wagmi/yarn.lock
- guides/drain-safe-app/app/package.json
- guides/drain-safe-app/app/yarn.lock
- packages/safe-apps-sdk/package.json
- yarn.lock
Upgraded viem and wagmi to v2. (wagmi v2 40% smaller)
> upgrade: viem and wagmi to v2

- .changeset/few-bobcats-beg.md
- examples/wagmi/yarn.lock
- guides/drain-safe-app/app/yarn.lock
- yarn.lock
> chore: bump dependencies

- packages/safe-apps-sdk/dist/cjs/version.js
- packages/safe-apps-sdk/dist/esm/version.js
- packages/safe-apps-sdk/src/version.ts
Push correct safe-apps-sdk version to repo
> chore(safe-apps-sdk): update wrong SDK version
