safe-global/safe-apps-sdk

README.md, package.json, src/index.ts, yarn.lock
When the SDK is initialized it requests the Safe web interface the information of the Safe.
There is no need to export this functionality because is enough if it's called during the initialization.
This allows to initialize the SDK some time after the app is loaded and the Safe web interface sends the Safe info for the first time.
Check https://github.com/gnosis/safe-react/pull/1138 to see the changes from the Safe web interface side
=> Request Safe info from a Safe app

src/index.ts, src/types.ts
This PR redefines the `Network` type as a union of `LowercaseNetworks` and `UppercaseNetworks`. 
Then the `network` key of `SafeInfo` type was changed to return `LowercaseNetworks`.
=> Split networks

README.md
Safe App developers should also be advised to add the providedBy information to the manifest. While we do not yet expose this information to users, we do plan to do so in the future: https://github.com/gnosis/safe-react/issues/514
=> Add providedBy manifest info to readme

packages/safe-apps-sdk/src/sdk.ts, packages/safe-apps-sdk/src/types.ts
When updating safe-react-apps I stumbled upon a bug where the return value of the network was in uppercase but the type was in lowercase
https://github.com/gnosis/safe-react/blob/0ecd70fdbcd94952ce82acd00dbfbaaaa4ec1f74/src/config/index.ts#L18
https://github.com/gnosis/safe-react/blob/0ecd70fdbcd94952ce82acd00dbfbaaaa4ec1f74/src/config/networks/network.d.ts
This PR fixes that by changing the type from lowercase to uppercase (faster than updating the interface and there's no real need to return the lowercase one)
=> Bug: Fix network type in safe info

README.md
Link pointing to `cra-template-safe-app` package in the README file was broken
=> Fix cra-template-safe-app link

packages/safe-apps-react-sdk/README.md, packages/safe-apps-react-sdk/package.json, packages/safe-apps-react-sdk/src/index.tsx, packages/safe-apps-sdk/package.json, packages/safe-apps-sdk/src/sdk.ts, packages/safe-apps-sdk/src/types.ts, yarn.lock
This PR:
- Fixes inconsistency between the type and actual returned value for `network` prop in `getSafeInfo`
=> Fix SafeInfo network type

packages/safe-apps-react-sdk/README.md, packages/safe-apps-react-sdk/package.json, packages/safe-apps-react-sdk/src/index.tsx, packages/safe-apps-sdk/package.json, packages/safe-apps-sdk/src/sdk.ts, packages/safe-apps-sdk/src/types.ts, yarn.lock
I fucked up a little by running `npm publish --beta` instead of `npm publish --tag beta` and packages got published as the latest versions 🤦 
- Fix network type in SafeInfo (https://github.com/gnosis/safe-apps-sdk/pull/78)
- Update to the SDK V1.0.3
=> 1.0.3 sdk and 1.0.1 react-sdk releases to master

packages/safe-apps-sdk/src/txs/index.ts
This PR:
- Throws an error if returned status code is other than 200
=> Bug: When calling getTxBySafeTxHash every status code is considered success

.github/workflows/cla.yml, README.md, package.json, packages/cra-template-safe-app/package.json, packages/cra-template-safe-app/template.json, packages/safe-apps-ethers-provider/README.md, packages/safe-apps-ethers-provider/package.json, packages/safe-apps-ethers-provider/src/index.ts, packages/safe-apps-ethers-provider/src/provider.ts, packages/safe-apps-ethers-provider/src/utils.ts, packages/safe-apps-react-sdk/package.json, packages/safe-apps-sdk/package.json, packages/safe-apps-sdk/src/txs/index.ts, yarn.lock
- Throw an error if transaction is not found in `sdk.txs.getBySafeTxHash` (https://github.com/gnosis/safe-apps-sdk/pull/96)
- use Safe Apps SDK v2.0.0
- use Safe Apps React SDK v2.0.0
- Bump `react-scripts` bersion
- use Safe Apps SDK v2.0.0
- Add ethers.js signer
**I will release everything after this PR gets approved**
=> Safe Apps Dev Tools Release 5

packages/cra-template-safe-app/template.json, packages/safe-apps-ethers-provider/package.json, packages/safe-apps-onboard/package.json, packages/safe-apps-provider/package.json, packages/safe-apps-provider/src/provider.ts, packages/safe-apps-react-sdk/package.json, packages/safe-apps-sdk/package.json, packages/safe-apps-sdk/src/eth/eth.test.ts, packages/safe-apps-sdk/src/eth/index.ts, packages/safe-apps-sdk/src/types.ts, packages/safe-apps-web3modal/package.json, yarn.lock
- Improve tx handling: If transaction was submitted via the provider, we will cache a fake tx to be returned in case we cannot load the real one.
- Remove web3-core dependency (TODO: cleanup yarn.lock after each package release)
=> Improve tx handling; remove web3-core dependency

packages/safe-apps-onboard/package.json, packages/safe-apps-provider/package.json, packages/safe-apps-provider/src/provider.ts, packages/safe-apps-web3-react/package.json, packages/safe-apps-web3modal/package.json, yarn.lock
This PR:
- Closes #128 by adding network id for xdai
In the future we will make the core sdk return the chain id, removing the need to add an id per network
=> Safe Apps Provider: Add xdai chain network id

.github/workflows/cla.yml, packages/safe-apps-provider/README.md
`@gnosis.pm/safe-apps-provider` exports `SafeAppProvider` and not `SafeAppsProvider` so I updated the `README` to reflect that
=> Update SafeAppProvider references in README.md

packages/safe-apps-sdk/tsconfig.json, tsconfig.json
The tests for the sdk are being included in the build outputs and increasing the size of the package whereas we can safely remove them.
=> Remove test files from build outputs

packages/safe-apps-onboard/package.json, packages/safe-apps-provider/package.json, packages/safe-apps-provider/src/provider.ts, packages/safe-apps-provider/src/types.ts, packages/safe-apps-web3-react/package.json, packages/safe-apps-web3modal/package.json
It turned out that our provider is not https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md compatible. In particular, it was missing events system, and connect/disconnect functionality. This PR fixes it
=> Feature: Make safe-app-provider follow eip1193 standard

packages/safe-apps-sdk/dist/package.json, packages/safe-apps-sdk/package.json, yarn.lock
We got a report that 58% of our bundle is semver: https://github.com/gnosis/safe-apps-sdk/issues/154
According to [bundlephobia](https://bundlephobia.com/result?p=semver@7.1.2), semver's bundle size increased 7times at version 7.1.2 and continued to grow since.
We're not using it heavily so I downgraded it to version 7.1.0 where it weighs 2kb: https://bundlephobia.com/result?p=semver@7.1.0
I used 7.1.0 because @types/semver are version 7.1.0 too, not sure if 7.1.1 is compatible with types 7.1.0
=> Decrease bundle size by downgrading semver

packages/safe-apps-sdk/src/communication/communicator.test.ts, packages/safe-apps-sdk/src/communication/index.ts, packages/safe-apps-sdk/src/eth/index.ts, packages/safe-apps-sdk/src/safe/index.ts, packages/safe-apps-sdk/src/txs/index.ts, packages/safe-apps-sdk/src/types/messaging.ts
Currently, each method would implement a handler for the error case by itself. This could be moved one layer higher to the communication implementation.
**This PR:**
- Moves error handling to the communicator
- Adds a test case
- removes error handlers from methods
=> Feature: Catch exceptions in communicator

packages/safe-apps-sdk/src/sdk.ts
This line will throw if you try to use it with Next.js for example. We want to support SSR, thus we remove this check
=> Remove check for window for SSR

packages/safe-apps-web3modal/README.md
The readme wasn't updated and contained outdated non-existent methods. This PR fixes that.
=> Update safe-app-web3modal readme

packages/safe-apps-react-sdk/README.md
The `Transaction` type does not exist anymore. It looks like it's been superseded by `BaseTransaction`.
=> docs: update transaction type in react sdk README

.github/workflows/release.yml
Related to #269 and the recent ban of automated publishing, I removed the npm token from the action, and their docs say it won't publish changes then. Let's merge it and test what it does instead
=> Remove npm token for changesets action

.changeset/wicked-yaks-try.md, packages/safe-apps-sdk/package.json, packages/safe-apps-sdk/src/types/gateway.ts, yarn.lock
Gateway client definitions were really outdated, with many types mismatchin client gateway responses. To avoid this in the future and unify efforts from all web teams we will use `safe-react-gateway-sdk` because it will be easier to keep up to date only in one place
=> Add safe-react-gateway-sdk for gateway types

.changeset/nasty-jokes-sparkle.md, packages/safe-apps-sdk/dist/package.json, packages/safe-apps-sdk/package.json, yarn.lock
Resolves #292 
Bumps dependencies for safe-react-gateway-sdk to 2.9.0
=> chore: bump gateway version

.changeset/rich-llamas-cry.md, packages/safe-apps-react-sdk/src/index.tsx
Fix a missing mandatory property in SafeInfo init for `safe-apps-react-sdk` package
=> fix(safe-apps-react-sdk): fix missing property `isReadOnly`

guides/drain-safe-app/03-transfer-assets.md, packages/cra-template-safe-app/template/public/manifest.json, packages/safe-apps-sdk/README.md
 
Fixes gnosis/safe-react-apps#313
 How this PR fixes it 
We are making `description` and `iconPath` properties optional. and adding support for the standard `icons` one
=> feat: Update docs to reflect manifest changes

.github/workflows/release.yml, .github/workflows/test.yml
some actions failed on development because they were using node 14
https://github.com/safe-global/safe-apps-sdk/runs/6964537043?check_suite_focus=true
=> Update node to 16 lts in github actions

.changeset/big-moons-repair.md, packages/safe-apps-react-sdk/package.json, packages/safe-apps-react-sdk/src/index.tsx
This PR:
- Adds support for react 18 in the react SDK. The only change needed was to add an explicit declaration for the `children` prop for the provider component. See change explanation here https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions
=> Support react 18 in react sdk

.changeset/stupid-moose-destroy.md, packages/safe-apps-provider/package.json, packages/safe-apps-react-sdk/package.json, packages/safe-apps-sdk/dist/package.json, packages/safe-apps-sdk/package.json, packages/safe-apps-wagmi/package.json, packages/safe-apps-web3-react/package.json, packages/safe-apps-web3modal/package.json
After upgrading the template to react-scripts 5, it has many errors because our packages include a source map in the build but not the source files this source maps reference.
Warning example:
```
WARNING in ./node_modules/@gnosis.pm/safe-apps-sdk/dist/src/txs/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/mmv/projects/gnosis/drain-safe/node_modules/@gnosis.pm/safe-apps-sdk/src/txs/index.ts' file: Error: ENOENT: no such file or directory, open '/Users/mmv/projects/gnosis/drain-safe/node_modules/@gnosis.pm/safe-apps-sdk/src/txs/index.ts'
```
After doing some research, it looks like it's a good practice to publish source files for typescript files and source maps for proper debugging support: …
=> Chore: include source files in npm package

packages/safe-apps-sdk/README.md
Something broke the formatting, and the sentence was cut off. This PR fixes that
=> safe-apps-sdk: fix constructor options docs

.changeset/friendly-students-tickle.md, packages/cra-template-safe-app/template.json
This PR:
Fixes #400 by downgrading the `@testing-library/react` library by one major version, so it is compatible with the version of `react` library we're using.
To test:
```
npx create-react-app my-safe-app --template file:../path-to-template
```
=> Downgrade `@testing-library/react` to the version supporting react 17

.changeset/mean-kiwis-add.md, packages/safe-apps-provider/src/provider.ts
Currently, it is not possible to populate the `safeTxGas` when using a safe app that communicates through the `SafeAppProvider` (e.g. WalletConnect).
This PR updates the Safe App Provider to forward the provided gas limit to `safeTxGas`. This is helpful in many cases where a gas buffer is required to avoid "Out of gas" errors.
=> Populate `safeTxGas` using the provided gas limit (`SafeAppProvider`)	

.changeset/forty-jokes-sing.md, packages/safe-apps-provider/package.json, packages/safe-apps-react-sdk/package.json, packages/safe-apps-sdk/dist/package.json, packages/safe-apps-sdk/package.json
This PR:
- Implements #500 
From the issue:
> Without "sideEffects" switched off (e.g. "sideEffects": false) build systems aren't able to properly eliminate dead code (e.g. Next.js) and could still load these packages even if they are not used.
More info: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
=> Feature: add `sideEffects` property to package.json to improve tree-shaking

README.md, package.json
Starting from `lerna` v7 they relay the dependency management completely to yarn or npm
=> Update lerna README instructions

.changeset/hungry-lizards-obey.md, packages/safe-apps-provider/CHANGELOG.md, packages/safe-apps-provider/package.json
This PR was opened by the [Changesets](https://github.com/gnosis/changesets-action-github-releases) GitHub action. When you\'re ready to do a release, you can merge this and publish to npm yourself. If you\'re not ready to do a release yet, that\'s fine, whenever you add more changesets to main, this PR will be updated.
-   d6baa64: fallback `value` and `data` were overwritten with `undefined`
=> Version Packages

.changeset/dry-parents-learn.md, packages/safe-apps-sdk/src/index.ts
Resolves #539.
Re-exports RPC_CALLS from the index file.
=> Fix: export RPC_CALLS from index

packages/safe-apps-sdk/README.md
Fix a misleading regex example as pointed out by an external contributor.
=> Docs: fix regex syntax in SDK examples

packages/safe-apps-sdk/README.md, packages/safe-apps-wagmi/README.md
Fix a misleading regex example as pointed out by an external contributor.
=> docs: fix regex syntax in SDK exapmples
